// src/app/im-sidebar/components/im-sidebar-header/im-sidebar-header.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'im-sidebar-header',
  templateUrl: './im-sidebar-header.component.html'
})
export class ImSidebarHeaderComponent implements OnInit {

  /**
   * 收起按钮的标题
   * @type {string}
   */
  @Input() title = '';

  /**
   * 总未读数
   * @type {number}
   */
  @Input() unread = 0;

  /**
   * 是否闪动
   * @type {boolean}
   */
  @Input() shake = false;

  constructor() {
  }

  ngOnInit() {
  }

}

<div class="jjsim-hd">
  <i class="jjsim-icon sprite sprite-dialog" [ngClass]="{shake:shake}">
    <span class="jjsim-hd-num">{{unread}}</span>
  </i>
  <span class="im-title">test</span>
  <a class="jjsim-hd-closebtn sprite sprite-down" title="展开"></a>
</div>

// src/main/components/im-sidebar-header/im-sidebar-header.component.tsx
import * as React from 'react';
import ImShake from '../im-shake/im-shake.component';

class ImSidebarHeaderComponent extends React.PureComponent<Props> {

  render() {
    const {title = '', up, unread, onClick, shake = false} = this.props;
    return (
      <div className="jjsim-hd" onClick={onClick}>
        <ImShake shake={shake} interval={500}>
          <i className="jjsim-icon sprite sprite-dialog shake">
            <span className={`jjsim-hd-num ${unread > 0 ? '' : 'hide'}`}>{unread}</span>
          </i>
        </ImShake>
        <span className="im-title">{title}</span>
        <a className={`jjsim-hd-closebtn sprite ${up ? 'sprite-down' : 'sprite-up'} ${up ? '' : 'hide'}`}/>
      </div>
    );
  }
}

export default ImSidebarHeaderComponent;

export interface Props {
  /**
   * 标题
   */
  title?: string;
  /**
   * 未读数据
   */
  unread: number;
  /**
   * 是否已经展开
   */
  up: boolean;
  /**
   * 是否闪动
   */
  shake: boolean;
  /**
   * 点击事件
   */
  onClick: () => void;
}
